### ISSUE TITLE
Get the name of a function

### ISSUE THREAD

**Issue by golsch** [athre0z/wasm#6]
How is it possible to get the associated name of the function body?

**Comment by athre0z** [comment]
IIRC, not every binary comes with with this information included. If they do, you can obtain them by passing `decode_name_subsections=True` to

https://github.com/athre0z/wasm/blob/5b5f17e31be78cd41afd86a8187ef72466e7bf35/wasm/decode.py#L32-L33

You should then encounter a 

https://github.com/athre0z/wasm/blob/5b5f17e31be78cd41afd86a8187ef72466e7bf35/wasm/modtypes.py#L200-L206

module fragment during iteration. One of these name sections would have a `NameMap` payload

https://github.com/athre0z/wasm/blob/5b5f17e31be78cd41afd86a8187ef72466e7bf35/wasm/modtypes.py#L185-L187

where the `names` fields would contain a list of

https://github.com/athre0z/wasm/blob/5b5f17e31be78cd41afd86a8187ef72466e7bf35/wasm/modtypes.py#L179-L182

where the `index` field corresponds to the function index and the `name_str` holds the function name.

Please take this with a grain of salt -- I haven't looked into this source base for a while. If you have any problems, feel free to provide me with an example binary and I'll see if I can hack together an example.

**Comment by golsch** [comment]
That sounds good. Thanks for your quick help. I tried your approach, but I am getting an error while decoding.

Traceback (most recent call last):
  File "test.py", line 35, in <module>
    for cur_sec, cur_sec_data in mod_iter:
  File "/Users/<>/wasm/wasm/decode.py", line 56, in decode_module
    subsec_len, subsec_data, _ = subsec.from_raw(None, sec_wnd)
  File "/Users/<>/wasm/wasm/types.py", line 302, in from_raw
    data_len, val, data_type = cur_field.from_raw(data, raw[offs:])
  File "/Users/<>/wasm/wasm/types.py", line 188, in from_raw
    return self.choice_field_map[choice].from_raw(ctx, raw)
KeyError: 806

Do you have any idea?

**Comment by athre0z** [comment]
Well, that's a decoding failure. 

The name section is what is called a [custom section](https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md#name-section) and can diverge from the wasm specification with the wasm module still remaining loadable. It is thus thinkable that your compiler made use of that freedom. It is also possible that my decoding for the standard name section is just bugged. You'll have to provide me with the binary if you want me to take a look.

You can either just attach it here or mail it to me at the mail you can find on my profile.

**Comment by athre0z** [comment]
Resolved via private mail.

For future public reference, here is a sample on how to associate functions with their names:

```python
from wasm import (
    decode_module,
    format_function,
    Section,
    NameSubSection,
    FunctionBody,
    SEC_IMPORT,
    SEC_CODE,
    SEC_NAME,
)

with open('function.wasm', 'rb') as raw:
     raw = raw.read()

mod_iter = iter(decode_module(raw, decode_name_subsections=True))
header, header_data = next(mod_iter)

fn_space = []
fn_names = {}

for cur_sec, cur_sec_data in mod_iter:
    if isinstance(cur_sec, Section):
        if cur_sec_data.id == SEC_IMPORT:
            for entry in cur_sec_data.payload.entries:
                module = entry.module_str.tobytes().decode()
                fn_name = entry.field_str.tobytes().decode()
                fn = f'import: {module}:{fn_name}'
                fn_space.append(fn)
        elif cur_sec_data.id == SEC_CODE:
            for entry in cur_sec_data.payload.bodies:
                fn_space.append(entry)

    elif isinstance(cur_sec, NameSubSection):
        for entry in cur_sec_data.payload.names:
            fn_names[entry.index] = entry.name_str.tobytes().decode()



for i, fn in enumerate(fn_space):
    print(f'============== [{fn_names[i]:^30}] ==============')

    if isinstance(fn, str):
        # imported function
        print(fn)
    else:
        # function with bytecode, implemented in the module
        print('\n'.join(format_function(fn)))

    print()
```
